# Request 1 processors on 1 node
#PBS -l nodes=1:ppn=1

# Request walltime (how long will your program run?)
#PBS -l walltime=24:00:00

# Request 1 gigabyte of memory per process
#PBS -l pmem=10gb

# send an email if the job aborts (a) and when it ends (e) 
#PBS -mae

# send the email to this address
#PBS -M fridolin.linder@gmail.com

# Request that regular output and terminal output go to the same file
#PBS -j oe

# Run your program
# don't forget to load the software modules you are using if necessary
cd $PBS_O_WORKDIR
python get_csv_alignment_scores.py
